services:
  - type: web
    name: bloomberg-terminal-mc
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
