services:
  - type: web
    name: vvip-signal-pro
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: PUPPETEER_CACHE_DIR
        value: "/opt/render/project/src/.cache"
